### PR TITLE
Replace many instances of com.google.inject with javax.inject

### PR DESCRIPTION
**Pull request by benmccann**
This makes many classes usable with other DI frameworks besides just Guice

### CODE REVIEW

**Comment by lukesandberg** [comment]
All these classes are internal implementation details of the renderer which
uses guice (references Injector,Guice classes).  Is there actually a
benefit to alternate DI frameworks?

**Comment by benmccann** [comment]
Yes, we couldn't easily make everything DI agnostic, but we can make quite a bit of it. I don't expect Google to maintain support for multiple DI frameworks, but if this change makes it easier for third parties then why not? It certainly doesn't hurt anything.

**Comment by lukesandberg** [comment]
Im just questioning why a 3rd party would want to inject any of these
classes?  they are implementation details.

I don't really have a problem with the change (switching everything to
javax.inject seems quite reasonable on its own), i am just trying to
understand what this might enable for a user.

**Comment by benmccann** [comment]
Ah, sorry, I misunderstood your original comment. There's not any immediate benefit besides perhaps just adhering to something that's a slightly better practice. I originally started looking at this because closure-templates used with a Guice 4.0 app errors out due to conflicting Guice versions.This change makes it much easier for me to see where Guice-specific functionality like AssistedInject is being used because I can grep for com.google.inject to get just Guice stuff without seeing all the generic DI stuff that's supported by javax. So really it's just a bit helpful for a Guice upgrade which is why I was interested.

The main benefit for now is probably just that it adheres closer to Google's cloding style. E.g. see this commit which did the same thing throughout google3 https://github.com/google/closure-templates/commit/4458fd961e8d374ab7560dc2ac2fccd135835a96

**Comment by Ubehebe** [comment]
@benmccann google3? :)

This is fine by me. You'll need to [sign a CLA](https://github.com/google/closure-templates/blob/master/CONTRIBUTING.md) first though.

**Comment by benmccann** [comment]
It's been awhile since I've been at Google. Maybe you're on google4 now? :)

I've signed the CLA for other projects in the past, so I think we should be all good there. E.g. here are two bugs on Closure Compiler showing that I signed it and had my patch committed:
https://code.google.com/p/closure-library/issues/detail?id=400
https://code.google.com/p/closure-compiler/issues/detail?id=650

Thanks so much for taking a look!

**Comment by benmccann** [comment]
Thanks!!

**Pull request merged**
