### PR TITLE
correct syntax error in conf of js-jar packaging

### PR DESCRIPTION
**Pull request by jmhodges**

### CODE REVIEW

**Comment by jmhodges** [comment]
Ping!

**Comment by mashedcode** [comment]
This looks right but it would be amazing if you could provide much more detail in your commit message and the description of your pull request.

* Could you link to the docs explicitly stating that this is the only correct syntax?
* Does it throw an error with the incorrect syntax or does it simply not work at all?

This would make it much easier to quickly review your PR without perfect knowledge of Maven and it would furthermore get anyone to understand if this is just a cosmetic change or if a real issue lies behind this PR.

Furthermore regrading your ping from my experience merging pull requests may take a couple days since they'll run build checks against all internal projects using the project you contribute to before they'll merge.

**Comment by mikesamuel** [comment]
I'll incorporate this into the next push.

**Comment by jmhodges** [comment]
This seems to have been handled in another PR and it's very old. Closing it out! Have a good one!

**Pull request closed without merging**
